########################(beg of [Makefile])########################
Library=./../..
###################################################################

comp::

###################################################################

clean:: ; rm -f *~

cleanall:: clean
cleanall:: ; rm -f *.class

###################################################################

comp:: ; javac -cp $(Library) FnA1sz.java
comp:: ; javac -cp $(Library) FnA1szUtil.java
comp:: ; javac -cp $(Library) FnA1szSUtil.java

########################(end of [Makefile])########################
