########################(beg of [Makefile])########################
Library=./../..
###################################################################

comp::

###################################################################

clean:: ; rm -f *~

cleanall:: clean
cleanall:: ; rm -f *.class

###################################################################

comp:: ; javac -cp $(Library) FnTupl2.java
comp:: ; javac -cp $(Library) FnTupl2SUtil.java

###################################################################

comp:: ; javac -cp $(Library) FnTupl3.java
comp:: ; javac -cp $(Library) FnTupl3SUtil.java

########################(end of [Makefile])########################
