########################(beg of [Makefile])########################
Library00=./../..
###################################################################

comp::

###################################################################

clean:: ; rm -f *~

cleanall:: clean
cleanall:: ; rm -f *.class

###################################################################

comp:: ; javac -cp .:$(Library00) LnStrm.java
comp:: ; javac -cp .:$(Library00) LnStcn.java
comp:: ; javac -cp .:$(Library00) LnStrmSUtil.java

########################(end of [Makefile])########################
